import {requireSupabase} from '../lib/supabase';import {normalizeError} from './errors';
export type Addon={id:string;name:string;description:string|null;price:number};
export type LiveOpening={id:string;service:string;start_at:string;end_at:string;duration_minutes:number;price:number;service_area:string|null;provider_name:string;average_rating:number;review_count:number;booking_method:'instant'|'provider_approval';scope:string[];excluded_scope:string[];addons:Addon[];expiration_at:string;property_size_limit:string|null;customer_requirements:string|null;restrictions:string|null;provider_verified:boolean;total_count:number};
export interface OpeningFilters{service?:string;date?:string;timeOfDay?:string;maximumPrice?:number;minimumRating?:number;bookingMethod?:'instant'|'provider_approval';postalCode?:string;sort?:'soonest'|'price'|'rating'|'newest';page?:number;pageSize?:number}
async function rpc<T>(name:string,args:Record<string,unknown>):Promise<T>{const {data,error}=await requireSupabase().rpc(name as never,args as never);if(error)throw normalizeError(error);return data as T}
export const openingService={
 async search(filters:OpeningFilters={}){const size=Math.min(filters.pageSize||20,50);return rpc<LiveOpening[]>('search_marketplace_openings',{p_service:filters.service||null,p_postal_code:filters.postalCode||null,p_date:filters.date||null,p_time_of_day:filters.timeOfDay||null,p_max_price:filters.maximumPrice??null,p_min_rating:filters.minimumRating??null,p_booking_method:filters.bookingMethod||null,p_sort:filters.sort||'soonest',p_limit:size,p_offset:((filters.page||1)-1)*size})},
 async detail(id:string){const rows=await this.search({pageSize:50});return rows.find(row=>row.id===id)||null},
 async mine(){const {data,error}=await requireSupabase().from('appointment_openings' as never).select('id,status,start_at,end_at,fixed_price,booking_method,starting_postal_code,expiration_at,provider_service_id').order('start_at',{ascending:false}).limit(100);if(error)throw normalizeError(error);return data as unknown as Array<Record<string,unknown>>},
 async create(input:{providerServiceId:string;startAt:string;durationMinutes:number;fixedPrice:number;postalCode:string;travelRadiusMiles:number;propertySizeLimit?:string;customerRequirements?:string;restrictions?:string;bookingMethod:'instant'|'provider_approval';expirationAt:string}){return rpc<Record<string,unknown>>('create_provider_opening',{p_provider_service_id:input.providerServiceId,p_start_at:input.startAt,p_duration_minutes:input.durationMinutes,p_fixed_price:input.fixedPrice,p_starting_postal_code:input.postalCode,p_travel_radius_miles:input.travelRadiusMiles,p_property_size_limit:input.propertySizeLimit||'',p_customer_requirements:input.customerRequirements||'',p_restrictions:input.restrictions||'',p_booking_method:input.bookingMethod,p_expiration_at:input.expirationAt})},
 setStatus:(id:string,action:'pause'|'reopen'|'cancel')=>rpc<Record<string,unknown>>('set_provider_opening_status',{p_opening_id:id,p_action:action}),
};
