import {requireSupabase} from '../lib/supabase';
import {normalizeError} from './errors';

export interface ProviderServiceSummary{id:string;name:string;description:string|null;starting_rate:number;rate_unit:string}
export interface PublicProvider{provider_id:string;display_name:string;headline:string|null;biography:string|null;years_experience:number|null;profile_image_path:string|null;business_logo_path:string|null;service_areas:string[];travel_radius_miles:number|null;languages:string[];availability_summary:string|null;payment_policy:string|null;cancellation_policy:string|null;custom_requests_enabled:boolean;average_rating:number;review_count:number;completed_booking_count:number;member_since:string;services:ProviderServiceSummary[];portfolio:Array<{id:string;storage_path:string;alt_text:string}>;earliest_opening:string|null;total_count:number}
const rpc=async<T>(name:string,args:Record<string,unknown>):Promise<T>=>{const{data,error}=await requireSupabase().rpc(name as never,args as never);if(error)throw normalizeError(error);return data as T};
export const providerProfileService={
 search:(filters:{service?:string;postalCode?:string;page?:number}={})=>rpc<PublicProvider[]>('search_provider_profiles',{p_service:filters.service||null,p_postal_code:filters.postalCode||null,p_limit:20,p_offset:((filters.page||1)-1)*20}),
 async get(id:string){const rows=await rpc<PublicProvider[]>('search_provider_profiles',{p_service:null,p_postal_code:null,p_limit:50,p_offset:0});return rows.find(x=>x.provider_id===id)||null},
 async update(input:Partial<{business_name:string;headline:string;public_biography:string;service_areas:string[];travel_radius_miles:number;languages:string[];availability_summary:string;payment_policy:string;cancellation_policy:string;custom_requests_enabled:boolean}>){const{data,error}=await requireSupabase().from('provider_profiles' as never).update(input as never).eq('user_id', (await requireSupabase().auth.getUser()).data.user?.id||'').select('user_id').single();if(error)throw normalizeError(error);return data},
 imageUrl(path:string){return requireSupabase().storage.from('provider-public-images').getPublicUrl(path).data.publicUrl},
 completeness(profile:Partial<PublicProvider>){const checks={photo:Boolean(profile.profile_image_path),headline:Boolean(profile.headline),biography:Boolean(profile.biography),service:Boolean(profile.services?.length),startingRate:Boolean(profile.services?.some(s=>s.starting_rate>=0)),serviceArea:Boolean(profile.service_areas?.length),availability:Boolean(profile.availability_summary),paymentPolicy:Boolean(profile.payment_policy),cancellationPolicy:Boolean(profile.cancellation_policy)};return{checks,percent:Math.round(Object.values(checks).filter(Boolean).length/Object.keys(checks).length*100)}}
};
