import {createClient} from 'https://esm.sh/@supabase/supabase-js@2.53.0';
import {cors,json,unix} from '../_shared/billing.ts';
const allowed=new Set(['checkout.session.completed','customer.subscription.created','customer.subscription.updated','customer.subscription.deleted','invoice.paid','invoice.payment_failed','customer.subscription.trial_will_end']);
const statuses=new Set(['trialing','active','past_due','unpaid','canceled','incomplete','incomplete_expired','paused']);
function equal(a:Uint8Array,b:Uint8Array){if(a.length!==b.length)return false;let result=0;for(let i=0;i<a.length;i++)result|=a[i]^b[i];return result===0}
async function verify(payload:string,header:string,secret:string){const parts=Object.fromEntries(header.split(',').map(x=>x.split('=',2))),timestamp=Number(parts.t);if(!timestamp||Math.abs(Date.now()/1000-timestamp)>300)return false;const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(secret),{name:'HMAC',hash:'SHA-256'},false,['sign']);const signed=new Uint8Array(await crypto.subtle.sign('HMAC',key,new TextEncoder().encode(`${timestamp}.${payload}`)));const expected=new Uint8Array((parts.v1||'').match(/.{2}/g)?.map(x=>parseInt(x,16))||[]);return equal(signed,expected)}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'method_not_allowed'},405);const payload=await req.text(),signature=req.headers.get('stripe-signature')||'',secret=Deno.env.get('STRIPE_WEBHOOK_SIGNING_SECRET')||'';if(!secret||!await verify(payload,signature,secret))return json({error:'invalid_signature'},400);let event:any;try{event=JSON.parse(payload)}catch{return json({error:'invalid_payload'},400)}if(!allowed.has(event.type))return json({received:true,ignored:true});const url=Deno.env.get('SUPABASE_URL'),role=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY');if(!url||!role)return json({error:'server_configuration'},500);const admin=createClient(url,role,{auth:{persistSession:false}});
 const {error:claim}=await admin.from('subscription_events').insert({stripe_event_id:event.id,event_type:event.type,source:'webhook',outcome:'processing'});if(claim?.code==='23505')return json({received:true,duplicate:true});if(claim)return json({error:'event_claim_failed'},500);
 try{const object=event.data.object,customer=typeof object.customer==='string'?object.customer:object.customer?.id;let subscriptionId=event.type.startsWith('customer.subscription')?object.id:typeof object.subscription==='string'?object.subscription:object.subscription?.id;let {data:record}=await admin.from('provider_subscriptions').select('id,user_id,plan_id').or(`stripe_subscription_id.eq.${subscriptionId||''},stripe_customer_id.eq.${customer||''}`).maybeSingle();const userId=object.metadata?.user_id||record?.user_id;
  if(event.type==='checkout.session.completed'&&record){await admin.from('provider_subscriptions').update({stripe_subscription_id:subscriptionId,updated_at:new Date().toISOString()}).eq('id',record.id)}
  if(event.type.startsWith('customer.subscription')&&record){const status=event.type==='customer.subscription.deleted'?'canceled':statuses.has(object.status)?object.status:'incomplete';const price=object.items?.data?.[0]?.price?.id;const {data:plan}=price?await admin.from('subscription_plans').select('id').eq('stripe_price_id',price).maybeSingle():{data:null};await admin.from('provider_subscriptions').update({stripe_subscription_id:object.id,stripe_price_id:price||null,plan_id:plan?.id||record.plan_id,status,trial_start:unix(object.trial_start),trial_end:unix(object.trial_end),current_period_start:unix(object.current_period_start),current_period_end:unix(object.current_period_end),cancel_at_period_end:Boolean(object.cancel_at_period_end),canceled_at:unix(object.canceled_at),updated_at:new Date().toISOString()}).eq('id',record.id)}
  if(record&&['invoice.payment_failed','customer.subscription.trial_will_end'].includes(event.type)){const failed=event.type==='invoice.payment_failed';await admin.from('notifications').insert({user_id:record.user_id,type:failed?'subscription_payment_failed':'subscription_trial_ending',title:failed?'Provider subscription payment failed':'Provider trial ending soon',message:failed?'Manage your OpenSlot provider billing in Stripe.':'Review your OpenSlot provider subscription before the trial ends.'})}
  await admin.from('subscription_events').update({provider_subscription_id:record?.id||null,user_id:userId||null,outcome:'processed',metadata:{stripe_object_id:object.id}}).eq('stripe_event_id',event.id);return json({received:true});
 }catch(error){console.error(error);await admin.from('subscription_events').update({outcome:'failed'}).eq('stripe_event_id',event.id);return json({error:'webhook_processing_failed'},500)}});
export {verify};
