-- OpenSlot v0.2: schema, integrity, RLS, transactional workflows and private storage.
create extension if not exists pgcrypto;
create type public.user_role as enum ('customer','provider','admin');
create type public.opening_status as enum ('draft','published','reserved','booked','paused','expired','cancelled');
create type public.booking_method as enum ('instant','provider_approval');
create type public.booking_status as enum ('requested','confirmed','declined','provider_en_route','in_progress','completed','customer_cancelled','provider_cancelled','disputed','refunded');
create type public.application_status as enum ('draft','pending','approved','rejected','paused','suspended','more_information');
create type public.review_status as enum ('active','hidden');

create table public.profiles(id uuid primary key references auth.users on delete cascade,role user_role not null default 'customer',display_name text,email text,phone text,avatar_path text,account_status text not null default 'active' check(account_status in('active','paused','suspended')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.addresses(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles on delete cascade,label text not null,address_line_1 text not null,address_line_2 text,city text not null,state text not null,postal_code text not null,latitude numeric,longitude numeric,is_default boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index one_default_address on addresses(user_id) where is_default;
create table public.customer_profiles(user_id uuid primary key references profiles on delete cascade,default_address_id uuid references addresses on delete set null,preferred_contact_method text check(preferred_contact_method in('email','phone','text')),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.provider_profiles(user_id uuid primary key references profiles on delete cascade,business_name text not null default '',business_description text,years_experience int check(years_experience>=0),travel_radius_miles numeric check(travel_radius_miles between 0 and 100),verification_status text not null default 'unreviewed',insurance_status text not null default 'unreviewed',application_status application_status not null default 'draft',application_reason text,average_rating numeric(2,1) not null default 0 check(average_rating between 0 and 5),review_count int not null default 0 check(review_count>=0),completed_job_count int not null default 0 check(completed_job_count>=0),instant_booking_enabled boolean not null default false,response_period_minutes int not null default 120 check(response_period_minutes between 15 and 1440),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.service_categories(id uuid primary key default gen_random_uuid(),slug text unique not null,name text not null,description text,icon text,active boolean not null default true,sort_order int not null default 0);
create table public.provider_services(id uuid primary key default gen_random_uuid(),provider_id uuid not null references provider_profiles on delete cascade,service_category_id uuid not null references service_categories,base_price numeric(10,2) not null check(base_price>=0),estimated_duration_minutes int not null check(estimated_duration_minutes>0),description text,included_work text[],excluded_work text[],active boolean not null default true,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(provider_id,service_category_id));
create table public.service_addons(id uuid primary key default gen_random_uuid(),provider_service_id uuid not null references provider_services on delete cascade,name text not null,description text,price numeric(10,2) not null check(price>=0),active boolean not null default true);
create table public.provider_availability(id uuid primary key default gen_random_uuid(),provider_id uuid not null references provider_profiles on delete cascade,start_at timestamptz not null,end_at timestamptz not null,availability_type text not null,notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_at>start_at));
create table public.appointment_openings(id uuid primary key default gen_random_uuid(),provider_id uuid not null references provider_profiles on delete cascade,provider_service_id uuid not null references provider_services,status opening_status not null default 'draft',booking_method booking_method not null,start_at timestamptz not null,end_at timestamptz not null,fixed_price numeric(10,2) not null check(fixed_price>=0),travel_radius_miles numeric check(travel_radius_miles between 0 and 100),starting_postal_code text,property_size_limit text,expiration_at timestamptz not null,customer_requirements text,restrictions text,published_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_at>start_at),check(expiration_at<=start_at));
create table public.bookings(id uuid primary key default gen_random_uuid(),confirmation_code text unique not null,opening_id uuid not null references appointment_openings,customer_id uuid not null references customer_profiles,provider_id uuid not null references provider_profiles,service_address_id uuid not null references addresses,status booking_status not null,service_subtotal numeric(10,2) not null check(service_subtotal>=0),addon_total numeric(10,2) not null check(addon_total>=0),booking_fee numeric(10,2) not null check(booking_fee>=0),estimated_tax numeric(10,2) not null check(estimated_tax>=0),total numeric(10,2) not null check(total>=0),provider_payout_estimate numeric(10,2) not null check(provider_payout_estimate>=0),property_size text,grass_height text,gate_access text,pets_present boolean not null default false,special_instructions text,preferred_contact_method text,provider_response_due_at timestamptz,decline_reason text,requested_at timestamptz not null default now(),accepted_at timestamptz,declined_at timestamptz,cancelled_at timestamptz,completed_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index one_live_booking_per_opening on bookings(opening_id) where status not in ('declined','customer_cancelled','provider_cancelled','refunded');
create table public.booking_addons(id uuid primary key default gen_random_uuid(),booking_id uuid not null references bookings on delete cascade,service_addon_id uuid references service_addons,name_snapshot text not null,price_snapshot numeric(10,2) not null check(price_snapshot>=0));
create table public.booking_photos(id uuid primary key default gen_random_uuid(),booking_id uuid not null references bookings on delete cascade,uploaded_by uuid not null references profiles,storage_path text unique not null,photo_type text,caption text,created_at timestamptz not null default now());
create table public.saved_providers(customer_id uuid references customer_profiles on delete cascade,provider_id uuid references provider_profiles on delete cascade,created_at timestamptz not null default now(),primary key(customer_id,provider_id));
create table public.reviews(id uuid primary key default gen_random_uuid(),booking_id uuid not null references bookings,customer_id uuid not null references customer_profiles,provider_id uuid not null references provider_profiles,quality_rating int not null check(quality_rating between 1 and 5),timeliness_rating int not null check(timeliness_rating between 1 and 5),communication_rating int not null check(communication_rating between 1 and 5),listing_accuracy_rating int not null check(listing_accuracy_rating between 1 and 5),value_rating int not null check(value_rating between 1 and 5),overall_rating numeric(2,1) generated always as ((quality_rating+timeliness_rating+communication_rating+listing_accuracy_rating+value_rating)::numeric/5) stored,review_text text,status review_status not null default 'active',created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create unique index one_active_review on reviews(booking_id) where status='active';
create table public.notifications(id uuid primary key default gen_random_uuid(),user_id uuid not null references profiles on delete cascade,type text not null,title text not null,message text not null,related_booking_id uuid references bookings on delete cascade,related_opening_id uuid references appointment_openings on delete cascade,read_at timestamptz,created_at timestamptz not null default now());
create table public.provider_documents(id uuid primary key default gen_random_uuid(),provider_id uuid not null references provider_profiles on delete cascade,document_type text not null,storage_path text unique not null,review_status text not null default 'pending',expiration_date date,reviewed_by uuid references profiles,reviewed_at timestamptz,created_at timestamptz not null default now());
create table public.support_cases(id uuid primary key default gen_random_uuid(),opened_by uuid not null references profiles,booking_id uuid references bookings,category text not null,subject text not null,description text not null,status text not null default 'open',assigned_admin_id uuid references profiles,resolution_notes text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.audit_events(id bigint generated always as identity primary key,actor_id uuid references profiles,event_type text not null,entity_type text not null,entity_id uuid,metadata jsonb not null default '{}',created_at timestamptz not null default now());
create index openings_marketplace on appointment_openings(status,start_at,expiration_at);create index bookings_customer on bookings(customer_id,created_at desc);create index bookings_provider on bookings(provider_id,created_at desc);create index notifications_user on notifications(user_id,read_at,created_at desc);

create function public.is_admin() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from profiles where id=auth.uid() and role='admin' and account_status='active')$$;
create function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into profiles(id,email,role) values(new.id,new.email,case when new.raw_user_meta_data->>'requested_role'='provider' then 'provider'::user_role else 'customer'::user_role end);if new.raw_user_meta_data->>'requested_role'='provider' then insert into provider_profiles(user_id) values(new.id);else insert into customer_profiles(user_id) values(new.id);end if;insert into notifications(user_id,type,title,message) values(new.id,'registration','Welcome to OpenSlot','Your in-app account is ready.');return new;end$$;
create trigger auth_user_profile after insert on auth.users for each row execute function handle_new_user();
create function public.protect_profile_privileges() returns trigger language plpgsql as $$begin if not is_admin() then new.role=old.role;new.account_status=old.account_status;new.email=old.email;end if;return new;end$$;
create trigger protect_profile before update on profiles for each row execute function protect_profile_privileges();
create function public.validate_booking_provider() returns trigger language plpgsql as $$begin if not exists(select 1 from appointment_openings o where o.id=new.opening_id and o.provider_id=new.provider_id) then raise exception 'provider mismatch';end if;return new;end$$;
create trigger booking_provider before insert or update on bookings for each row execute function validate_booking_provider();

create function public.create_booking(p_opening_id uuid,p_service_address_id uuid,p_property_size text default null,p_grass_height text default null,p_gate_access text default null,p_pets_present boolean default false,p_special_instructions text default null,p_preferred_contact_method text default null,p_addon_ids uuid[] default '{}') returns setof bookings language plpgsql security definer set search_path=public as $$declare o appointment_openings; b bookings; addon_sum numeric; code text;begin select * into o from appointment_openings where id=p_opening_id for update;if o.id is null or o.status<>'published' or o.expiration_at<=now() then raise exception using errcode='P0001',message='opening_unavailable';end if;if not exists(select 1 from addresses where id=p_service_address_id and user_id=auth.uid()) then raise exception 'invalid address';end if;select coalesce(sum(price),0) into addon_sum from service_addons where id=any(p_addon_ids) and provider_service_id=o.provider_service_id and active;code='OS-'||to_char(now(),'YYYY')||'-'||upper(substr(replace(gen_random_uuid()::text,'-',''),1,8));insert into bookings(confirmation_code,opening_id,customer_id,provider_id,service_address_id,status,service_subtotal,addon_total,booking_fee,estimated_tax,total,provider_payout_estimate,property_size,grass_height,gate_access,pets_present,special_instructions,preferred_contact_method,provider_response_due_at) values(code,o.id,auth.uid(),o.provider_id,p_service_address_id,case when o.booking_method='instant' then 'confirmed' else 'requested' end,o.fixed_price,addon_sum,4.99,round((o.fixed_price+addon_sum)*.06,2),o.fixed_price+addon_sum+4.99+round((o.fixed_price+addon_sum)*.06,2),round((o.fixed_price+addon_sum)*.88,2),p_property_size,p_grass_height,p_gate_access,p_pets_present,p_special_instructions,p_preferred_contact_method,case when o.booking_method='provider_approval' then now()+interval '2 hours' end) returning * into b;update appointment_openings set status=case when o.booking_method='instant' then 'booked' else 'reserved' end,updated_at=now() where id=o.id;insert into booking_addons(booking_id,service_addon_id,name_snapshot,price_snapshot) select b.id,id,name,price from service_addons where id=any(p_addon_ids);insert into notifications(user_id,type,title,message,related_booking_id,related_opening_id) values(auth.uid(),'booking_created','Booking received','Your booking is stored in OpenSlot.',b.id,o.id),(o.provider_id,'new_booking','New booking','A customer booked your opening.',b.id,o.id);return next b;end$$;
create function public.transition_booking(p_booking_id uuid,p_new_status booking_status,p_reason text default null) returns bookings language plpgsql security definer set search_path=public as $$declare b bookings;actor user_role;allowed boolean:=false;begin select * into b from bookings where id=p_booking_id for update;select role into actor from profiles where id=auth.uid();allowed=(actor='provider' and b.provider_id=auth.uid() and ((b.status='requested' and p_new_status in('confirmed','declined'))or(b.status='confirmed' and p_new_status in('provider_en_route','provider_cancelled'))or(b.status='provider_en_route' and p_new_status='in_progress')or(b.status='in_progress' and p_new_status='completed')))or(actor='customer' and b.customer_id=auth.uid() and ((b.status='requested' and p_new_status='customer_cancelled')or(b.status='confirmed' and p_new_status='customer_cancelled')) )or actor='admin';if not allowed then raise exception 'invalid status transition';end if;update bookings set status=p_new_status,accepted_at=case when p_new_status='confirmed' then now() else accepted_at end,declined_at=case when p_new_status='declined' then now() else declined_at end,cancelled_at=case when p_new_status in('customer_cancelled','provider_cancelled') then now() else cancelled_at end,completed_at=case when p_new_status='completed' then now() else completed_at end,decline_reason=case when p_new_status='declined' then p_reason else decline_reason end,updated_at=now() where id=b.id returning * into b;update appointment_openings set status=case when p_new_status='confirmed' then 'booked' when p_new_status in('declined','customer_cancelled') and start_at>now() then 'published' else status end where id=b.opening_id;insert into audit_events(actor_id,event_type,entity_type,entity_id,metadata) values(auth.uid(),'booking_status_changed','booking',b.id,jsonb_build_object('to',p_new_status,'reason',p_reason));return b;end$$;
create function public.validate_review() returns trigger language plpgsql as $$begin if not exists(select 1 from bookings where id=new.booking_id and customer_id=auth.uid() and provider_id=new.provider_id and status='completed') or new.customer_id<>auth.uid() then raise exception 'review not eligible';end if;return new;end$$;create trigger review_eligibility before insert on reviews for each row execute function validate_review();

alter table profiles enable row level security;alter table customer_profiles enable row level security;alter table provider_profiles enable row level security;alter table addresses enable row level security;alter table service_categories enable row level security;alter table provider_services enable row level security;alter table service_addons enable row level security;alter table provider_availability enable row level security;alter table appointment_openings enable row level security;alter table bookings enable row level security;alter table booking_addons enable row level security;alter table booking_photos enable row level security;alter table saved_providers enable row level security;alter table reviews enable row level security;alter table notifications enable row level security;alter table provider_documents enable row level security;alter table support_cases enable row level security;alter table audit_events enable row level security;
create policy own_or_admin_profiles on profiles for select using(id=auth.uid() or is_admin());create policy own_profile_update on profiles for update using(id=auth.uid() or is_admin());
create policy own_customer_profile on customer_profiles for all using(user_id=auth.uid() or is_admin()) with check(user_id=auth.uid() or is_admin());create policy own_addresses on addresses for all using(user_id=auth.uid() or is_admin()) with check(user_id=auth.uid() or is_admin());
create policy provider_public_read on provider_profiles for select to authenticated using(application_status='approved' or user_id=auth.uid() or is_admin());create policy provider_own_update on provider_profiles for update using(user_id=auth.uid() or is_admin());
create policy categories_read on service_categories for select to authenticated using(active or is_admin());create policy services_read on provider_services for select to authenticated using(active or provider_id=auth.uid() or is_admin());create policy services_manage on provider_services for all using(provider_id=auth.uid() or is_admin()) with check(provider_id=auth.uid() or is_admin());create policy addons_read on service_addons for select to authenticated using(active or is_admin());
create policy availability_manage on provider_availability for all using(provider_id=auth.uid() or is_admin()) with check(provider_id=auth.uid() or is_admin());
create policy openings_read on appointment_openings for select to authenticated using((status='published' and expiration_at>now() and exists(select 1 from provider_profiles p where p.user_id=provider_id and p.application_status='approved'))or provider_id=auth.uid() or is_admin());create policy openings_manage on appointment_openings for all using(provider_id=auth.uid() or is_admin()) with check((provider_id=auth.uid() and (status<>'published' or exists(select 1 from provider_profiles where user_id=auth.uid() and application_status='approved')))or is_admin());
create policy booking_participants_read on bookings for select using(customer_id=auth.uid() or provider_id=auth.uid() or is_admin());
create policy booking_children_read on booking_addons for select using(exists(select 1 from bookings b where b.id=booking_id and (b.customer_id=auth.uid() or b.provider_id=auth.uid()))or is_admin());create policy photos_participants on booking_photos for select using(exists(select 1 from bookings b where b.id=booking_id and (b.customer_id=auth.uid() or b.provider_id=auth.uid()))or is_admin());
create policy saves_own on saved_providers for all using(customer_id=auth.uid() or is_admin()) with check(customer_id=auth.uid() or is_admin());create policy reviews_read on reviews for select to authenticated using(status='active' or customer_id=auth.uid() or is_admin());create policy reviews_insert on reviews for insert with check(customer_id=auth.uid());create policy notifications_own on notifications for select using(user_id=auth.uid() or is_admin());create policy notifications_mark_read on notifications for update using(user_id=auth.uid());create policy documents_provider_admin on provider_documents for all using(provider_id=auth.uid() or is_admin()) with check(provider_id=auth.uid() or is_admin());create policy support_parties on support_cases for all using(opened_by=auth.uid() or assigned_admin_id=auth.uid() or is_admin()) with check(opened_by=auth.uid() or is_admin());create policy audit_admin on audit_events for select using(is_admin());

grant execute on function create_booking to authenticated;grant execute on function transition_booking to authenticated;
insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('avatars','avatars',false,5242880,array['image/jpeg','image/png','image/webp']),('booking-photos','booking-photos',false,8388608,array['image/jpeg','image/png','image/webp']),('provider-documents','provider-documents',false,10485760,array['application/pdf','image/jpeg','image/png']) on conflict(id) do nothing;
create policy avatar_owner on storage.objects for all using(bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text) with check(bucket_id='avatars' and (storage.foldername(name))[1]=auth.uid()::text);
create policy booking_photo_access on storage.objects for select using(bucket_id='booking-photos' and exists(select 1 from booking_photos p join bookings b on b.id=p.booking_id where p.storage_path=name and (b.customer_id=auth.uid() or b.provider_id=auth.uid() or is_admin())));
create policy booking_photo_upload on storage.objects for insert with check(bucket_id='booking-photos' and (storage.foldername(name))[1]=auth.uid()::text);
create policy private_provider_documents on storage.objects for all using(bucket_id='provider-documents' and ((storage.foldername(name))[1]=auth.uid()::text or is_admin())) with check(bucket_id='provider-documents' and ((storage.foldername(name))[1]=auth.uid()::text or is_admin()));
