import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,type ReactNode} from 'react';
import type {Session,User} from '@supabase/supabase-js';
import {authService,type RegistrationRole,normalizeAuthError} from '../services/authService';
import {profileService,type Profile,type ProviderProfile} from '../services/profileService';

type AuthContextValue={session:Session|null;user:User|null;profile:Profile|null;role:Profile['role']|null;accountStatus:string|null;providerApplicationStatus:ProviderProfile['application_status']|null;isAuthenticated:boolean;isLoading:boolean;profileLoading:boolean;authError:string|null;signUp:(i:{email:string;password:string;fullName:string;role:RegistrationRole})=>Promise<{needsVerification:boolean}>;signIn:(e:string,p:string)=>Promise<void>;signInWithOAuth:(p:'google'|'apple')=>Promise<void>;selectInitialRole:(r:'customer'|'provider')=>Promise<void>;signOut:()=>Promise<void>;requestPasswordReset:(e:string)=>Promise<void>;updatePassword:(p:string)=>Promise<void>;resendVerification:(e:string)=>Promise<void>;refreshProfile:()=>Promise<void>};
const AuthContext=createContext<AuthContextValue|null>(null);
export function AuthProvider({children}:{children:ReactNode}){const [session,setSession]=useState<Session|null>(null),[profile,setProfile]=useState<Profile|null>(null),[provider,setProvider]=useState<ProviderProfile|null>(null),[isLoading,setLoading]=useState(true),[profileLoading,setProfileLoading]=useState(false),[authError,setError]=useState<string|null>(null);const fetchRef=useRef<Promise<void>|null>(null);
 const refreshProfile=useCallback(async()=>{if(fetchRef.current)return fetchRef.current;const job=(async()=>{setProfileLoading(true);try{let found:Profile|null=null;for(let i=0;i<4&&!found;i++){found=await profileService.loadCurrentProfile();if(!found)await new Promise(r=>setTimeout(r,250*(i+1)))}setProfile(found);setProvider(found?.role==='provider'?await profileService.loadProviderProfile():null);if(!found)setError('Your account is signed in, but its OpenSlot profile is not ready. Try again shortly.')}catch(e){setError(normalizeAuthError(e).message)}finally{setProfileLoading(false);fetchRef.current=null}})();fetchRef.current=job;return job},[]);
 useEffect(()=>{let alive=true;authService.getSession().then(async({session:s})=>{if(!alive)return;setSession(s);if(s)await refreshProfile()}).catch(e=>setError(normalizeAuthError(e).message)).finally(()=>alive&&setLoading(false));const {data:{subscription}}=authService.subscribeToAuthChanges((event,s)=>{if(!alive)return;setSession(s);if(!s){setProfile(null);setProvider(null)}else if(event==='SIGNED_IN'||event==='USER_UPDATED')void refreshProfile()});return()=>{alive=false;subscription.unsubscribe()}},[refreshProfile]);
 const value=useMemo<AuthContextValue>(()=>({session,user:session?.user??null,profile,role:profile?.role??null,accountStatus:profile?.account_status??null,providerApplicationStatus:provider?.application_status??null,isAuthenticated:Boolean(session),isLoading,profileLoading,authError,async signUp(i){setError(null);try{const {session:s}=await authService.signUp(i);setSession(s);if(s)await refreshProfile();return{needsVerification:!s}}catch(e){const x=normalizeAuthError(e);setError(x.message);throw x}},async signIn(e,p){setError(null);try{const {session:s}=await authService.signIn(e,p);setSession(s);await refreshProfile()}catch(x){const e=normalizeAuthError(x);setError(e.message);throw e}},async signInWithOAuth(p){setError(null);try{await authService.signInWithOAuth(p)}catch(x){const e=normalizeAuthError(x);setError(e.message);throw e}},async selectInitialRole(r){setError(null);try{await profileService.selectInitialRole(r);await refreshProfile()}catch(x){const e=normalizeAuthError(x);setError(e.message);throw e}},async signOut(){setError(null);try{await authService.signOut();setSession(null);setProfile(null);setProvider(null)}catch(e){setError(normalizeAuthError(e).message);throw e}},async requestPasswordReset(e){try{await authService.requestPasswordReset(e)}catch(x){setError(normalizeAuthError(x).message);throw x}},async updatePassword(p){try{await authService.updatePassword(p)}catch(x){setError(normalizeAuthError(x).message);throw x}},async resendVerification(e){try{await authService.resendVerification(e)}catch(x){setError(normalizeAuthError(x).message);throw x}},refreshProfile}),[session,profile,provider,isLoading,profileLoading,authError,refreshProfile]);return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>}
export function useAuth(){const value=useContext(AuthContext);if(!value)throw new Error('useAuth must be used inside AuthProvider');return value}
